on:
  push:
    branches:
      - main
      - master

name: chrome-print-batch

jobs:
  chrome-print-batch:
    runs-on: macOS-latest

    strategy:
      fail-fast: false

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: release

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Install dependencies
        run: |
          install.packages('remotes')
          remotes::install_github('rstudio/pagedown')
        shell: Rscript {0}

      - name: Run batch
        run: Rscript script.R

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: chrome-logs
          path: './*.log'
